// ===== 记录层：初始示例数据 =====
// 覆盖：治疗中、已完成、急诊冻结、连续爽约进联系名单等典型情形。
import type { TreatmentPlan } from "./types";

const now = () => new Date().toISOString();
const daysAgo = (days: number, hour = 10): string => {
  const date = new Date();
  date.setDate(date.getDate() - days);
  date.setHours(hour, 0, 0, 0);
  return date.toISOString();
};

export function seedPlans(): TreatmentPlan[] {
  return [
    {
      id: "seed-54",
      toothNo: "#54",
      childName: "李小满",
      age: 5,
      diagnosis: "急性牙髓炎",
      stage: "medication",
      plannedVisits: 3,
      attendedVisits: 2,
      consecutiveNoShows: 0,
      guardianName: "李建国（父亲）",
      guardianRelation: "父亲",
      guardianPhone: "138****2041",
      guardianConfirmed: false,
      confirmNote: "",
      visitOutcome: "pending",
      emergency: { active: false, reason: "", at: "", resolved: false },
      contact: null,
      history: [
        { at: daysAgo(14), action: "初诊登记，预计 3 次完成" },
        { at: daysAgo(14), action: "到诊 #1：开髓、封药" },
        { at: daysAgo(7), action: "到诊 #2：更换封药（陪同改为父亲）" },
      ],
      createdAt: daysAgo(14),
    },
    {
      id: "seed-75",
      toothNo: "#75",
      childName: "王朵朵",
      age: 6,
      diagnosis: "慢性根尖周炎",
      stage: "crown",
      plannedVisits: 4,
      attendedVisits: 4,
      consecutiveNoShows: 0,
      guardianName: "王芳（母亲）",
      guardianRelation: "母亲",
      guardianPhone: "139****8830",
      guardianConfirmed: true,
      confirmNote: "母亲确认预成冠方案",
      visitOutcome: "attended",
      emergency: { active: false, reason: "", at: "", resolved: false },
      contact: null,
      history: [
        { at: daysAgo(21), action: "初诊登记，预计 4 次完成" },
        { at: daysAgo(21), action: "到诊 #1：局麻、开髓" },
        { at: daysAgo(14), action: "到诊 #2：清理冲洗、封药" },
        { at: daysAgo(7), action: "到诊 #3：根管充填" },
        { at: daysAgo(0, 9), action: "到诊 #4：本次到诊已登记" },
      ],
      createdAt: daysAgo(21),
    },
    {
      id: "seed-84",
      toothNo: "#84",
      childName: "赵一鸣",
      age: 4,
      diagnosis: "牙髓坏死伴牙龈肿胀",
      stage: "cleaning",
      plannedVisits: 4,
      attendedVisits: 1,
      consecutiveNoShows: 0,
      guardianName: "赵磊（父亲）",
      guardianRelation: "父亲",
      guardianPhone: "137****5521",
      guardianConfirmed: false,
      confirmNote: "",
      visitOutcome: "pending",
      emergency: {
        active: true,
        reason: "颊侧明显肿胀、患儿诉疼痛，本次转急诊处理，根管计划保留",
        at: daysAgo(0, 8),
        resolved: false,
      },
      contact: null,
      history: [
        { at: daysAgo(10), action: "初诊登记，预计 4 次完成" },
        { at: daysAgo(10), action: "到诊 #1：开髓、初步冲洗" },
        { at: daysAgo(0, 8), action: "明显疼痛肿胀，本次转急诊，原计划保留待重排" },
      ],
      createdAt: daysAgo(10),
    },
    {
      id: "seed-64",
      toothNo: "#64",
      childName: "陈思齐",
      age: 5,
      diagnosis: "慢性牙髓炎",
      stage: "access",
      plannedVisits: 3,
      attendedVisits: 1,
      consecutiveNoShows: 2,
      guardianName: "陈静（姑姑）",
      guardianRelation: "姑姑（临时陪同）",
      guardianPhone: "135****7766",
      guardianConfirmed: false,
      confirmNote: "",
      visitOutcome: "noshow",
      emergency: { active: false, reason: "", at: "", resolved: false },
      contact: {
        method: "电话",
        note: "连续两次未到，父母电话未接，改约周末由母亲陪同",
        scheduledAt: daysAgo(0, 11),
        contactedAt: daysAgo(0, 11),
        rescheduled: false,
      },
      history: [
        { at: daysAgo(20), action: "初诊登记，预计 3 次完成" },
        { at: daysAgo(20), action: "到诊 #1：局麻、开髓" },
        { at: daysAgo(13), action: "未到诊 #1（连续 1 次）" },
        { at: daysAgo(6), action: "未到诊 #2（连续 2 次），进入联系名单" },
        { at: daysAgo(0, 11), action: "联系名单：已电话沟通，待确认重排" },
      ],
      createdAt: daysAgo(20),
    },
    {
      id: "seed-55",
      toothNo: "#55",
      childName: "林小可",
      age: 6,
      diagnosis: "乳牙深龋近髓",
      stage: "done",
      plannedVisits: 2,
      attendedVisits: 2,
      consecutiveNoShows: 0,
      guardianName: "林敏（母亲）",
      guardianRelation: "母亲",
      guardianPhone: "186****1029",
      guardianConfirmed: true,
      confirmNote: "母亲确认充填完成",
      visitOutcome: "attended",
      emergency: { active: false, reason: "", at: "", resolved: false },
      contact: null,
      history: [
        { at: daysAgo(30), action: "初诊登记，预计 2 次完成" },
        { at: daysAgo(30), action: "到诊 #1：开髓、封药" },
        { at: daysAgo(23), action: "到诊 #2：充填、修复，家长确认，计划完成" },
      ],
      createdAt: daysAgo(30),
    },
  ];
}
